{% set name = "artifacts-keyring" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 22559cb6de86a1c062c0d81aa638ab046aceb8362db01b1a60c04040d8915438

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4
    - pip
    - setuptools
    - wheel
  run:
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4
    - keyring >=16.0
    - requests >=2.20.0

test:
  imports:
    - artifacts_keyring
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/microsoft/artifacts-keyring/
  summary: '"Automatically retrieve credentials for Azure Artifacts."'
  description: |
    The artifacts-keyring package provides authentication for publishing
    or consuming Python packages to or from Azure Artifacts feeds within Azure DevOps.
    This package is an extension to keyring, which will automatically find and use it once installed.
    Both pip and twine will use keyring to find credentials.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
    - src/artifacts_keyring/plugins/LICENSE
  doc_url: https://github.com/microsoft/artifacts-keyring?tab=readme-ov-file#usage
  dev_url: https://github.com/microsoft/artifacts-keyring/

extra:
  recipe-maintainers:
    - dokick
